version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - .:/app
    depends_on:
      - voicevox
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    tty: true
